### ISSUE TITLE
EPIC: As an end-user I would like to have a more performant version of mobility.meran.eu

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/mobility.meran.eu#40]
- [ ] based on webcomponent bus by Daniel R. (when fixed, see https://github.com/noi-techpark/bdp-commons/issues/104)
- [ ] integration of other mobility layers, as in mobility.meran.eu, using APIv2
- [ ] configurable so to allow an easy deployment for mobility.bz.it (logo, map basic centering)
